[package]
name = "password"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rpassword = "7.3.1"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }